#!/bin/bash

if [ $# -eq 1 ]; then
    FILE=$1
else
    exit 0
fi

OUTFILE=test.tmp

while read LINE;
do
    SIZE=$(echo "$LINE" | cut -d ":" -f1)
    NAME=$(echo "$LINE" | cut -d ":" -f2)
    FULLPATH=$(echo "$LINE" | cut -d ":" -f3)
    HASH=$(echo "$LINE" | cut -d ":" -f4)
    TYPE=$(echo "$LINE" | cut -d ":" -f5)
    
    echo $HASH:$LINE >> $OUTFILE
done < $FILE
